FROM node:22-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

RUN npx ng build components && \
    npx ng build api && \
    npx ng build features && \
    npx ng build teams --configuration azure

FROM nginx:alpine

COPY --from=build /app/dist/teams/browser /usr/share/nginx/html
COPY nginx/teams.conf.template /etc/nginx/templates/default.conf.template

EXPOSE 80

ENV PORT=80
ENV API_GATEWAY_URL=http://api-gateway
